# requirements.yaml
dependencies:
- name: elasticsearch-operator
  version: "0.1.3"
  repository: "https://raw.githubusercontent.com/upmc-enterprises/elasticsearch-operator/master/charts/"
- name: fluent-bit
  version: "0.12.0"
  repository: "https://kubernetes-charts.storage.googleapis.com"
- name: kibana
  version: "0.14.7"
  repository: "https://kubernetes-charts.storage.googleapis.com"
