psp:
  enabled: true

elasticsearch-operator:
  rbac:
    enabled: true
  image:
    repository: liviudm/elasticsearch-operator
    tag: v0.2.0-sa1
    pullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

fluent-bit:
  rbac:
    create: true
  image:
    fluent_bit:
      repository: fluent/fluent-bit
      tag: 0.13.0
  backend:
    type: es
    es:
      host: elasticsearch-efk
      port: 9200
      tls: off

kibana:
  image:
    repository: "docker.elastic.co/kibana/kibana-oss"
    tag: "6.1.3"
    pullPolicy: "IfNotPresent"
  serviceAccountName: kibana
  env:
    ELASTICSEARCH_URL: http://elasticsearch-efk:9200
    SERVER_PORT: 5601
    LOGGING_VERBOSE: "true"
    SERVER_DEFAULTROUTE: "/app/kibana"
  files:
    kibana.yml:
      server.name: kibana
      server.host: "0"
      elasticsearch.url: http://elasticsearch-efk:9200
  ingress:
    enabled: false
  livenessProbe:
    enabled: false
    initialDelaySeconds: 30
    timeoutSeconds: 10
  readinessProbe:
    enabled: false
    initialDelaySeconds: 30
    timeoutSeconds: 10
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 768Mi
  dashboardImport:
    xpackauth:
      enabled: false

elasticsearch:
  image: 
    repository: "upmcenterprises/docker-elasticsearch-kubernetes"
    tag: "6.1.3_0"
  clientReplicas: 1
  masterReplicas: 1
  dataReplicas: 1
  dataVolumeSize: 64Gi
  javaOpts: "-Xms512m -Xmx512m"
  useSsl: false
  serviceAccountName: elasticsearch
  snapshot:
    enabled: false
  storage:
    storageClass: "gp2"
    reclaimPolicy: "Delete"
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: '1'
