{{- if not (.Capabilities.APIVersions.Has "enterprises.upmc.com/v1") }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: elasticsearchclusters.enterprises.upmc.com
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: enterprises.upmc.com
  names:
    kind: ElasticsearchCluster
    listKind: ElasticsearchClusterList
    plural: elasticsearchclusters
    singular: elasticsearchcluster
  scope: Namespaced
  version: v1
{{- end }}
