{{- if .Values.psp.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
  name: {{ .Values.elasticsearch.serviceAccountName }}
---
{{- if .Capabilities.APIVersions.Has "policy/v1beta1" }}
apiVersion: policy/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: PodSecurityPolicy
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
  name: psp-elasticsearch-{{ .Release.Name }}
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - 'IPC_LOCK'
  seLinux:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - 'configMap'
  - 'emptyDir'
  - 'projected'
  - 'secret'
  - 'downwardAPI'
  - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
  name: psp-elasticsearch-{{ .Release.Name }}
rules:
  - apiGroups:
    - extensions
    {{- if .Capabilities.APIVersions.Has "policy/v1beta1" }}
    - policy
    {{- end }}
    resources:
    - podsecuritypolicies
    resourceNames:
    - psp-elasticsearch-{{ .Release.Name }}
    verbs:
    - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
  name: psp-elasticsearch-{{ .Release.Name }}
roleRef:
  kind: ClusterRole
  name: psp-elasticsearch-{{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Values.elasticsearch.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
{{- end }}
